plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'me.modmuss50.mod-publish-plugin' version '2.1.1'
}

def properties = new Properties()
file('../../gradle.properties').withInputStream { properties.load(it) }
file('gradle.properties').withInputStream { properties.load(it) }
properties.each { key, value -> ext.set(key.toString(), value.toString()) }

group = mod_group_id
version = mod_version

base {
    archivesName = "${mod_name}-neoforge-26.1"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

neoForge {
    version = neoforge_261_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation project(':common')
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version: neoforge_261_minecraft_version,
            neoforge_version: neoforge_261_version,
            neoforge_version_range: neoforge_261_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    from project(':common').sourceSets.main.output
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

apply from: file('../../gradle/target-conventions/publish.gradle')
