buildscript {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.10.5'
        classpath 'me.modmuss50:mod-publish-plugin:2.1.1'
    }
}

apply plugin: 'fabric-loom'
apply plugin: 'java'
apply plugin: 'me.modmuss50.mod-publish-plugin'

def properties = new Properties()
file('../../gradle.properties').withInputStream { properties.load(it) }
file('gradle.properties').withInputStream { properties.load(it) }
properties.each { key, value -> ext.set(key.toString(), value.toString()) }

group = mod_group_id
version = mod_version

base {
    archivesName = "${mod_name}-fabric-1.20.1"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

sourceSets.main.output.dir(
        project(':common').layout.buildDirectory.dir('classes/java/main'),
        builtBy: ':common:classes'
)

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${fabric_minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation project(':common')
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version: fabric_minecraft_version,
            fabric_loader_version: fabric_loader_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties
    filesMatching('fabric.mod.json') {
        expand replaceProperties + [project: project]
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

apply from: file('../../gradle/target-conventions/publish.gradle')
